appId    = ""
password = ""
environmentName = "Demo"
location = "West US"
nodeCount = 2
aks_subnet_cidr = "10.224.0.0/16"
azure_subscription_id = ""
azure_sp_tenant_id = ""
trident_location = "westus"